### ISSUE TITLE
Frame incorrectly inserted in UISpecialFrames

### ISSUE THREAD

**Issue by Solanya** [tmg-pub/listener#1]
https://github.com/tmg-pub/listener/blob/9e05b985dcb5ff64189be813a009a075ac81e713/addon/ui/CopyFrame.xml#L37

UISpecialFrames should only contain frame names and not frames directly. The line should be `table.insert( UISpecialFrames, self:GetName() )` instead.

**Comment by tmg-pub** [comment]
ah frick...

**Comment by tmg-pub** [comment]
fixed ty
