### ISSUE TITLE
Consider hosting addon outside of CurseForge

### ISSUE THREAD

**Issue by jharrell** [tmg-pub/listener#2]
Hi there, 

I, and many others, use third party addon managers and are not keen on switching over to Overwolf/CurseForge's first party addon manager. Would it be possible to host listener outside of CurseForge? I am happy to assist in a pull request that will utilize the [BigWigs Packager](https://github.com/BigWigsMods/packager) in order to upload a zip to GitHub, or an alternative source of monetization like [wago.io](https://addons.wago.io/)

Thank you for considering!

**Comment by tmg-pub** [comment]
hi, this is done
added automation to release to github and wago.io
