### ISSUE TITLE
Publish release with new TOC Interface version

### ISSUE THREAD

**Issue by Kumodatsu** [tmg-pub/listener#3]
Hey,

The latest release for Listener has an old Interface version in the TOC file, so it's listed as an out of date addon.
It seems to be working just fine though, so it would be nice if a new release could be published with the most recent Interface version (though since, at the time of writing this, a new WoW patch will release soon, it could wait until then too).

If I understand the GitHub workflow and the forgepush project correctly, I think only a new tag has to be pushed, but I might be wrong.

The same appears to be the case for your other project, [Emote Splitter](https://github.com/tmg-pub/emote-splitter)

**Comment by tmg-pub** [comment]
there you go bestie

**Comment by Kumodatsu** [comment]
Thank you very much!
